services:
  mkdocs:
    build:
      context: .
      dockerfile: ./ops/docker/mkdoc/Dockerfile
    environment:
        PLANTUML_SERVER_URL: http://plantuml:8080/plantuml
    volumes:
      - ./docs:/docs/docs
      - ./README.md:/docs/README.md
      - ./mkdocs.yml:/docs/mkdocs.yml
      - ./site:/docs/site
    ports:
      - "8000:8000"
    command: mkdocs serve --dev-addr=0.0.0.0:8000 --livereload
    links:
      - plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
    environment:
      BASE_URL: plantuml
